version: '3.0'

services:
  postgres:
    container_name: postgres_database
    image: postgres:15.1
    volumes:
      - ./postgres-db:/var/lib/postgresql/data
    restart: always
    ports:
      - "5433:5433"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=test_db
      

  pgAdmin:
    depends_on:
      - postgres
    image: dpage/pgadmin4:6.17
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_PASSWORD=123456
      - PGADMIN_DEFAULT_EMAIL=cristhianingsis@gmail.com

volumes:
  postgres-db:
    external: true